-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgzwauycAsQRdwhyxr
Ts0OozCfIqsa0LB9BcCdfX0VZ1ugCgYIKoZIzj0DAQehRANCAARgtcXiYVzwNR1o
/C2hrUCT1a+t0dz2QlmnrFtSejObhv8Lqj3Gh2v5dMw9uPY2kBvNkDfKiTyNfWGr
q0SHKk5E
-----END PRIVATE KEY-----